---
apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Kill the cstor target/Jiva controller container and check if gets created again
kind: ChaosExperiment
metadata:
  labels:
    litmuschaos.io/name: openebs
  name: openebs-target-failure
  version: 0.1.1
spec:
  definition:
    image: "litmuschaos/ansible-runner:ci"
    args:
    - -c
    - ansible-playbook ./experiments/openebs/openebs-target-failure/openebs_target_failure_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:
    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

    - name: APP_PVC
      value: ''

    - name: OPENEBS_NAMESPACE
      value: 'openebs'

    - name: CONTAINER_RUNTIME
      value: 'docker' 

    - name: FORCE
      value: 'true'

    - name: LIB_IMAGE
      value: 'gaiaadm/pumba:0.4.8'

    - name: DATA_PERSISTENCE
      value: ''

    - name: LIVENESS_APP_LABEL
      value: ''

    - name: LIVENESS_APP_NAMESPACE
      value: ''

   # CHAOS_TYPE values :  target-zrepl-kill , target-kill , target-delete , jiva-ctrl-kill
    - name: CHAOS_TYPE
      value: "target-zrepl-kill"

   # TARGET_CONTAINER values: cstor-volume-mgmt , cstor-istgt
    - name: TARGET_CONTAINER
      value: "cstor-volume-mgmt"

    - name: DEPLOY_TYPE
      value: "deployment"

    labels:
      name: openebs-target-failure
    configmaps:
    - name: target-failure
      data:
        parameters.yml: |
