apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2020-04-14T10:28:08Z
  name: mercedes
  version: 0.1.3
  annotations:
    categories: Mercedes
    chartDescription: Injects kubernetes pod-delete chaos 
spec:
  displayName: Mercedes Chaos
  categoryDescription: >
   Cassandra is a free and open-source, distributed, wide column store, NoSQL database management system designed to handle 
   large amounts of data across many commodity servers, providing high availability with no single point of failure. 
   It will install all the experiments which can be used to inject chaos into cassandra applications.
  experiments:
    - mer-pod-delete
  keywords:
    - Kubernetes
    - Pod
    - Cassandra
    - Statefulset
  maintainers:
    - name: ksatchit
      email: karthik.s@mayadata.io
  minKubeVersion: 1.12.0
  provider:
    name: Mayadata
  links:
    - name: Kubernetes Website
      url: https://kubernetes.io
    - name: Cassandra Website
      url: http://cassandra.apache.org/
    - name: Source Code
      url: https://github.com/apache/cassandra
    - name: Cassandra Slack
      url: https://cassandra-slack.herokuapp.com
    - name: Documentation
      url: http://cassandra.apache.org/doc/latest/
  icon:
    - url: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/mercedes/icons/mercedes.png
      mediatype: image/png
  chaosexpcrdlink: https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/mercedes/experiments.yaml
