---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mer-pod-delete-sa
  namespace: default
  labels:
    name: mer-pod-delete-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mer-pod-delete-sa
  namespace: default
  labels:
    name: mer-pod-delete-sa
rules:
  - apiGroups: 
      - "" 
      - "batch" 
      - "litmuschaos.io"
    resources: 
      - "jobs" 
      - "pods" 
      - "chaosengines" 
      - "chaosexperiments" 
      - "chaosresults"
    verbs: 
      - "create" 
      - "list" 
      - "get" 
      - "update" 
      - "patch" 
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mer-pod-delete-sa
  namespace: default
  labels:
    name: mer-pod-delete-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mer-pod-delete-sa
subjects:
- kind: ServiceAccount
  name: mer-pod-delete-sa
  namespace: default