apiVersion: litmuschaos.io/v1alpha1
description:
  message: |
    Kills a container belonging to an application pod
kind: ChaosExperiment
metadata:
  name: container-kill
  version: 0.1.1
spec:
  definition:
    image: "litmuschaos/ansible-runner:ci"
    args:
    - -c
    - ansible-playbook ./experiments/generic/container_kill/container_kill_ansible_logic.yml -i /etc/ansible/hosts -vv; exit 0
    command:
    - /bin/bash
    env:
    - name: ANSIBLE_STDOUT_CALLBACK
      value: 'default'

    # only pumba supported
    # For pumba image use : gaiaadm/pumba:0.4.8
    - name: LIB_IMAGE  
      value: 'gaiaadm/pumba:0.4.8' 
         
    - name: TARGET_CONTAINER
      value: ''

    labels:
      name: container-kill